parameters:
  env(JAEGER_HOST): localhost
  env(JAEGER_PORT): 6832
  env(JAEGER_BUFFER_SIZE): 16384
  env(OPENTRACE_SAMPLER_RATE): 0.001
  env(JAEGER_CONTEXT_FORMAT): 'text'
  env(JAEGER_CONTEXT_ENV): 'UBER_TRACE_ID'
  env(JAEGER_CONTEXT_HEADER): 'uber-trace-id'
  env(JAEGER_DEBUG_ENV): 'JAEGER_DEBUG'
  env(JAEGER_DEBUG_COOKIE): 'jaeger_debug'
  service_name: app
services:
  spl.stack:
    class: SplStack
    shared: false
  spl.priority.queue:
    class: SplPriorityQueue
    shared: false
  id.generator.random:
    class: Jaeger\Id\RandomIntGenerator
  id.generator.span: '@id.generator.random'
  jaeger.codec.text:
    class: Jaeger\Codec\TextCodec
    tags:
      - {name: 'jaeger.codec', alias: 'text'}
  jaeger.codec.registry:
    class: Jaeger\Codec\CodecRegistry
    calls:
      -
        method: offsetSet
        arguments: ['text', '@jaeger.codec.text']
  jaeger.sampler.always:
    class: Jaeger\Sampler\ConstSampler
    arguments: [true]
  jaeger.sampler.const:
    class: Jaeger\Sampler\ConstSampler
    arguments: ['%kernel.debug%']
  jaeger.sampler.probabilistic:
    class: Jaeger\Sampler\ProbabilisticSampler
    arguments: ['%env(OPENTRACE_SAMPLER_RATE)%']
  jaeger.sampler: '@jaeger.sampler.probabilistic'
  jaeger.span.factory:
    class: Jaeger\Span\Factory\SpanFactory
    arguments: ['@id.generator.span', '@jaeger.sampler']
  client.thrift:
    class: Jaeger\Client\ThriftClient
    arguments: ['%service_name%', '@thrift.agent']
  thrift.agent:
    class: Jaeger\Thrift\Agent\AgentClient
    arguments: ['@thrift.protocol']
  thrift.protocol.compact:
    class: Thrift\Protocol\TCompactProtocol
    arguments: ['@thrift.transport']
  thrift.protocol.binary:
    class: Thrift\Protocol\TBinaryProtocol
    arguments: ['@thrift.transport']
  thrift.protocol: '@thrift.protocol.binary'
  thrift.transport.udp:
    class: Jaeger\Transport\TUDPTransport
    arguments: ['%env(JAEGER_HOST)%', '%env(JAEGER_PORT)%']
  thrift.transport.buffered:
    class: Thrift\Transport\TBufferedTransport
    arguments: ['@thrift.transport.udp', '%env(JAEGER_BUFFER_SIZE)%', '%env(JAEGER_BUFFER_SIZE)%']
    calls:
      -
        method: open
        arguments: []
  thrift.transport: '@thrift.transport.udp'
  jaeger.tracer:
    class: Jaeger\Tracer\Tracer
    arguments: ['@spl.stack', '@jaeger.span.factory', '@client.thrift']
  jaeger.context.extractor.env:
    class: Jaeger\Symfony\Context\Extractor\EnvContextExtractor
    arguments:
      - '@jaeger.codec.registry'
      - '%env(JAEGER_CONTEXT_FORMAT)%'
      - '%env(JAEGER_CONTEXT_ENV)%'
    tags:
      - {name: 'kernel.event_subscriber' }
      - {name: 'jaeger.context.extractor'}
  jaeger.context.extractor.header:
    class: Jaeger\Symfony\Context\Extractor\HeaderContextExtractor
    arguments:
      - '@jaeger.codec.registry'
      - '%env(JAEGER_CONTEXT_FORMAT)%'
      - '%env(JAEGER_CONTEXT_HEADER)%'
    tags:
      - {name: 'kernel.event_subscriber' }
      - {name: 'jaeger.context.extractor'}
  jaeger.context.extractor.chain:
    class: Jaeger\Symfony\Context\Extractor\ContextExtractorChain
    arguments:
      - '@spl.priority.queue'
  jaeger.context.extractor:
    alias: 'jaeger.context.extractor.chain'
  jaeger.debug.extractor.env:
    class: Jaeger\Symfony\Debug\Extractor\EnvDebugExtractor
    arguments:
      - '%env(JAEGER_DEBUG_ENV)%'
    tags:
      - {name: 'kernel.event_subscriber' }
      - {name: 'jaeger.debug.extractor'}
  jaeger.debug.extractor.cookie:
    class: Jaeger\Symfony\Debug\Extractor\CookieDebugExtractor
    arguments:
      - '%env(JAEGER_DEBUG_COOKIE)%'
    tags:
      - {name: 'kernel.event_subscriber' }
      - {name: 'jaeger.debug.extractor'}
  jaeger.debug.extractor.chain:
    class: Jaeger\Symfony\Debug\Extractor\DebugExtractorChain
    arguments:
      - '@spl.priority.queue'
  jaeger.debug.extractor:
    alias: 'jaeger.debug.extractor.chain'
  jaeger.debug.listener:
    class: Jaeger\Symfony\Bridge\DebugListener
    arguments:
      - '@jaeger.tracer'
      - '@jaeger.debug.extractor'
    tags:
      - {name: 'kernel.event_subscriber' }
  jaeger.context.listener:
    class: Jaeger\Symfony\Bridge\ContextListener
    arguments:
      - '@jaeger.tracer'
      - '@jaeger.context.extractor'
    tags:
      - {name: 'kernel.event_subscriber' }
  jaeger.request.span.listener:
    class: Jaeger\Symfony\Bridge\RequestSpanListener
    arguments:
      - '@spl.stack'
      - '@jaeger.tracer'
    tags:
      - {name: 'kernel.event_subscriber' }
  jaeger.app.start.listener:
    class: Jaeger\Symfony\Bridge\AppStartSpanListener
    arguments: ['@jaeger.tracer']
    tags:
      - {name: 'kernel.event_subscriber' }
  jaeger.tracer.bridge.symfony:
    class: Jaeger\Symfony\Bridge\TracerBridge
    arguments: ['@jaeger.tracer']
    tags:
      - {name: 'kernel.event_subscriber' }
