parameters:
  env(thrift_host): localhost
  env(thrift_port): 6831
  env(thrift_buffer_size): 16384
  env(opentrace_sampler_rate): 0.01
  env(jaeger_context_format): 'text'
  env(jaeger_context_env): 'UBER_TRACE_ID'
  env(jaeger_context_header): 'uber-trace-id'
services:
  spl.stack:
    class: \SplStack
    shared: false
  id.generator.random:
    class: Jaeger\Id\RandomIntGenerator
  id.generator.span: '@id.generator.random'
  jaeger.codec.text:
    class: Jaeger\Codec\TextCodec
    tags:
      - {name: 'jaeger.codec', alias: 'text'}
  jaeger.codec.registry:
    class: Jaeger\Codec\CodecRegistry
    calls:
      -
        method: offsetSet
        arguments: ['text', '@jaeger.codec.text']
  jaeger.sampler.always:
    class: Jaeger\Sampler\ConstSampler
    arguments: [true]
  jaeger.sampler.const:
    class: Jaeger\Sampler\ConstSampler
    arguments: ['%kernel.debug%']
  jaeger.sampler.probabilistic:
    class: Jaeger\Sampler\ProbabilisticSampler
    arguments: ['%env(opentrace_sampler_rate)%']
  jaeger.sampler: '@jaeger.sampler.probabilistic'
  jaeger.span.factory:
    class: Jaeger\Span\Factory\SpanFactory
    arguments: ['@id.generator.span', '@jaeger.sampler']
  client.thrift:
    class: Jaeger\Client\ThriftClient
    arguments: ['%service_name%', '@thrift.agent']
  thrift.agent:
    class: Jaeger\Thrift\Agent\AgentClient
    arguments: ['@thrift.protocol']
  thrift.protocol.compact:
    class: Thrift\Protocol\TCompactProtocol
    arguments: ['@thrift.transport']
  thrift.protocol.binary:
    class: Thrift\Protocol\TBinaryProtocol
    arguments: ['@thrift.transport']
  thrift.protocol: '@thrift.protocol.compact'
  thrift.transport.udp:
    class: Jaeger\Transport\TUDPTransport
    arguments: ['%env(thrift_host)%', '%env(thrift_port)%']
  thrift.transport.buffered:
    class: Thrift\Transport\TBufferedTransport
    arguments: ['@thrift.transport.udp', '%env(thrift_buffer_size)%', '%env(thrift_buffer_size)%']
    calls:
      -
        method: open
        arguments: []
  thrift.transport: '@thrift.transport.buffered'
  jaeger.tracer:
    class: Jaeger\Tracer\Tracer
    arguments: ['@spl.stack', '@jaeger.span.factory', '@client.thrift']
  jaeger.context.injector:
    class: Jaeger\Symfony\Bridge\ContextInjector
    arguments:
      - '@spl.stack'
      - '@jaeger.tracer'
      - '@jaeger.tracer'
      - '@jaeger.codec.registry'
      - '@request_stack'
      - '@router'
      - '%env(jaeger_context_format)%'
      - '%env(jaeger_context_env)%'
      - '%env(jaeger_context_header)%'
    tags:
      - {name: 'kernel.event_subscriber' }
  symfony.jaeger.tracer.bridge:
    class: Jaeger\Symfony\Bridge\TracerBridge
    arguments: ['@jaeger.tracer']
    tags:
      - {name: 'kernel.event_subscriber' }
